# Generated by Django 4.1.5 on 2023-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('channel_catagory', models.CharField(max_length=100)),
                ('channel_banner', models.ImageField(upload_to='img/')),
                ('channel_logo', models.ImageField(upload_to='img/')),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
