# Generated by Django 4.1.5 on 2023-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0002_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
