# Generated by Django 4.1.5 on 2023-01-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0004_alter_creator_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='github',
            field=models.CharField(default='', max_length=500),
        ),
    ]
