# Generated by Django 4.1.5 on 2023-01-04 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0005_creator_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('video', models.FileField(upload_to='videos/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
