# Generated by Django 4.1.5 on 2023-01-04 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('codectionaryapp', '0007_content_rating_content_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='codectionaryapp.creator'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
