# Generated by Django 4.1.5 on 2023-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0008_content_creator_content_tags_content_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_uploaded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
