# Generated by Django 4.1.5 on 2023-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0009_content_date_uploaded_alter_content_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.CharField(auto_created=True, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
