# Generated by Django 4.1.5 on 2023-01-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0010_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codectionaryapp.creator'),
        ),
    ]
