# Generated by Django 4.1.5 on 2023-01-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0011_alter_content_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
