# Generated by Django 4.1.5 on 2023-01-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0012_alter_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
    ]
