# Generated by Django 4.1.5 on 2023-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0013_remove_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='github',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='linkedin',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
