# Generated by Django 4.1.5 on 2023-01-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0014_content_github_content_linkedin_content_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codectionaryapp.creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='channel_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
