# Generated by Django 4.1.5 on 2023-01-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0016_content_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
