# Generated by Django 4.1.5 on 2023-01-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0017_alter_content_likes_alter_content_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
