# Generated by Django 4.1.5 on 2023-01-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0019_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('liker', models.IntegerField(default=1, editable=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codectionaryapp.content')),
            ],
        ),
    ]
