# Generated by Django 4.1.5 on 2023-01-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0020_alter_like_liker_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='view',
            name='liker',
        ),
    ]
