# Generated by Django 4.1.5 on 2023-01-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0021_remove_like_liker_remove_view_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codectionaryapp.creator'),
        ),
    ]
