# Generated by Django 4.1.5 on 2023-01-11 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codectionaryapp', '0023_like_time_view_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateField(auto_now=True)),
                ('follow_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow_to', to='codectionaryapp.creator')),
                ('followed_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
