# Generated by Django 4.1.5 on 2023-01-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codectionaryapp', '0026_content_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
